### ISSUE TITLE
一部分值无法获取到

### ISSUE THREAD

**Issue by lafitecao** [qiueer/zabbix#11]
一部分正常 一部分获取不到  在本机用命令 都为空
 python jvm.py -b 'java.lang:type=MemoryPool' -k 'name=CMS Old Gen",Usage.max' -p 13080
 python jvm.py -b 'java.lang:type=MemoryPool' -k 'Usage.max' -p 13080

![qq 20170612174742](https://user-images.githubusercontent.com/29372470/27028553-ac45b240-4f97-11e7-86fc-7e9447a201fd.png)

**Comment by lafitecao** [comment]
貌似 name=CMS Old Gen 是$3  Usage.max 是$4

**Comment by qiueer** [comment]
正常的，因为有好几种GC算法，但同时只能有一种生效（已验证），一个GC算法同时包含两个垃圾收集器，可以通过jconsole验证

**Comment by qiueer** [comment]
@lafitecao 周末做了更新，你可以使用新的配置。根据GC算法来做自动发现了。
