### ISSUE TITLE
在出现带逗号或双引号的参数时,无法将双引号带过去

### ISSUE THREAD

**Issue by ghost** [qiueer/zabbix#13]
jmx.tomcat.item["Catalina:type=ThreadPool,name="http-nio2-8080",currentThreadCount,12345]

在出现带逗号或双引号的参数时,无法将双引号带过去,导致参数错误,不知道是否是由于逗号的原因.jvm.py 和tomcat.py中同样遇到这个问题.

**Comment by qiueer** [comment]
jvm.py/tomcat.py做了特殊处理的。从你给的key看，有误。用以下的试下：
```
jmx.tomcat.item['Catalina:type=ThreadPool,name="http-nio2-8080"',currentThreadCount,12345]  或者
jmx.tomcat.item["Catalina:type=ThreadPool,name='http-nio2-8080'",currentThreadCount,12345]
```
