### ISSUE TITLE
您好,zabbix报告有些有数据,有些收不到数据.

### ISSUE THREAD

**Issue by zliangbj** [qiueer/zabbix#18]
您好, 
按照您的tomcat目录的guide指导,搭建了监控tomcat. 现在是监控页面的jmx/jmx tomcat数据能正常显示出来,而有些不能, 提示Received value [] is not suitable for value type [Numeric (float)]. 请问这个该怎么处理?
版本信息如下: 
   zabbix_proxy (Zabbix) 3.2.7
   Apache Tomcat/8.0.39
架构信息:
   zabbix server - zabbix proxy - zabbix agent
   agent 上面起了两个实例,使用两个jmx端口进行通信.
不能获取数据的例子:
jmx.jvm.item["java.lang:type=GarbageCollector,name=Copy",CollectionCount,17006]
jmx.tomcat.item["Catalina:type=Manager,path=/,host=localhost",activeSessions,17006]
谢谢!

**Comment by qiueer** [comment]
你好。
```
1）jmx.jvm.item["java.lang:type=GarbageCollector,name=Copy",CollectionCount,17006]
确认下你用是哪种GC算法
2）jmx.tomcat.item["Catalina:type=Manager,path=/,host=localhost",activeSessions,17006]
确认下tomcat的配置，是否配置
```

**Comment by zliangbj** [comment]
哦 ， 好了。 谢谢！
