### ISSUE TITLE
value should be a JSON object

### ISSUE THREAD

**Issue by kgqian** [qiueer/zabbix#2]

**Comment by kgqian** [comment]
你好，我使用你的tomcat自动发现脚本，zabbix报value should be a JSON object错误，请问怎么解决的额

**Comment by qiueer** [comment]
你是手工执行的吗，如果是，可以加多一个参数“-d”，把日志打印出来看看，估计是文件权限的问题。可以执行FAQ中的关于文件权限赋权的命令再看下

**Comment by qiueer** [comment]
https://github.com/qiueer/zabbix/tree/master/All%20In%20One
可以参考下这个路径的说明，逐步排查下

**Comment by kgqian** [comment]
可以加个qq么，527889833 ，麻烦详细指导以下，谢谢

**Comment by fireice009** [comment]
同样的问题。导致 Items 没有自动加到 Hosts 的 Items 里面。 
直接在 shell 直接执行，已经得到正常结果。并且 /tmp/.zabbix_redis_6379.txt 和 /tmp/zabbix_redis_info.log 有数据了，数据也是正常的。

```
[root@localhost scripts]# python redis.py -k used_memory
3785344

```

**Comment by fireice009** [comment]
做了以下三步，成功了。还没来得及测试具体哪一步是必须的。
* 授权
```
        echo "zabbix ALL=(root) NOPASSWD:/bin/netstat" > /etc/sudoers.d/zabbix
        echo 'Defaults:zabbix   !requiretty'  >>  /etc/sudoers.d/zabbix
        chmod 600  /etc/sudoers.d/zabbix
```
* [root@xxx]# setenforce 0  // 最好想办法授权，而不是直接关掉。
* redis.py 
`return json.dumps({'data': data}, sort_keys=True, indent=7, separators=(",",":"))`
改成
`return json.dumps({'data': data})`

**Comment by qiueer** [comment]
@fireice009  在root用户下手动执行“python redis.py -k used_memory”通常不会有什么问题，因为root的权限最大，你可以试下先在root用户下执行，然后切换到普通用户再执行看下效果。你做了三个步骤，需要确认一下，你启动zabbix_agentd是用哪个用户，第二、三个步骤应该没啥用。

**Comment by fireice009** [comment]
@qiueer 确实如你所说，在另外一台机上执行第一步就ok了。
