### ISSUE TITLE
can not find java command

### ISSUE THREAD

**Issue by zliangbj** [qiueer/zabbix#20]
您好, 

使用了您提供的all in one脚本安装配置了api/tomcat(同一个机器上)的监控(已启动相应的jmx端口).
zabbix-agent使用的yum安装方式进行安装的, 使用root启动,以系统自建的zabbix用户(不能登录)运行. 并在/etc/profile文件中申明了java的环境变量. 
现有以下问题想咨询下, 麻烦您了!

1. 使用Qiueer-LLD-JVM-Generic 模板进行tomcat监控出现了can not find java command问题.
请问该如何处理? 谢谢!
已经采取过手动建立zabbix的家目录,并创建.bash_profile,以申明java环境变量. 但问题依旧. 谢谢!

2. api/tomcat使用的jmx端口是否需要能被zabbix server访问?

谢谢!

**Comment by qiueer** [comment]
```
1、看报错应是找不到java命令导致，可以查看/tmp目录下的日志确认下，最直接的方法是将java命令做个软连接到这三个目录下：/usr/local/bin、/bin、/usr/bin
2、不需要，这个采集是agent做的
```
