### ISSUE TITLE
nginx 监控问题

### ISSUE THREAD

**Issue by zliangbj** [qiueer/zabbix#28]
您好, 

请问ALL In One下nginx使用的那个模板? 
官方的模板:Template App NGINX, 好像并没有自动发现功能.
使用官方模板导致/tmp/nginx_perf.log日志文件并没有生成.
只有使用命令: python nginx.py --list 该日志才会产生,但是也不会自动翻滚. 
请问这是什么导致的呢?
谢谢!

**Comment by qiueer** [comment]
```
python nginx.py --list是在root用户下执行的吗，应该是权限的问题，修改下日志的权限，例如：chmod 666 /tmp/nginx_perf.log。通常zabbix_agent是用zabbix用户运行。
```

**Comment by zliangbj** [comment]
是的呀 , zabbix的sudo权限也已经赋予了. /tmp/nginx_perf.log权限也没问题. 如果使用官方的模板监控的话, /tmp/nginx_perf.log的日志就一直不会有变化, 一直只有root手动执行后得输出

**Comment by qiueer** [comment]
```
o，我明白你的意思了，我这个模板跟zabbix官方提供的不一样的。官方提供的没有自动发现功能，我也没怎么研究...
```

**Comment by zliangbj** [comment]
额 那你用哪个模板, 能让日志自动变化?

**Comment by qiueer** [comment]
```
没能看明白你的意思，方便的话你加我微信吧，QiuJQin
```

**Comment by zliangbj** [comment]
请问, 使用all in one的nginx.conf监控设置后, zabbix应该使用nginx监控模板是哪个.
All in one里头并没有提供nginx的监控模板. 使用官方的nginx模板的话,则/tmp/nginx_perf.log 也不会有变化, zabbix的nginx监控也就没有数据了.

**Comment by qiueer** [comment]
```
之前电脑坏了。nginx模板已上传
```
