### ISSUE TITLE
Qiueer-LLD-JMX-Tomcat不能自动发现。

### ISSUE THREAD

**Issue by RyanZhang2015** [qiueer/zabbix#30]
你好， 我在执行python tomcat.py --list报如下错误。
Traceback (most recent call last):
File "tomcat.py", line 251, in main
print zbx_ex_obj.get_port_list()
File "tomcat.py", line 112, in get_port_list
parser.parse(server_xml)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
xmlreader.IncrementalParser.parse(self, source)
File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
self.feed(buffer)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
self._parser.Parse(data, isFinal)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
self._cont_handler.startElement(name, AttributesImpl(attrs))
File "tomcat.py", line 34, in startElement
protocal = attributes["protocol"]
File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 316, in getitem
return self._attrs[name]
KeyError: 'protocol'

但是运行python tomcat.py -b "Catalina:type=ThreadPool,name=http-bio-8090" -k currentThreadCount -p 12345可以拿到值。
这大概是什么问题呢。最关键问题是Qiueer-LLD-JMX-Tomcat自动发现没工作，在Info那有红色感叹号提示“Value should be a JSON object ”.
![image](https://user-images.githubusercontent.com/16250160/34240520-b6bf9e2c-e649-11e7-873d-6b5257dd9e5b.png)

**Comment by qiueer** [comment]
```1）检查下server.xml是否有误，例如用IE打开看下能否正常解析；
2）修改tomcat配置文件权限，让运行zabbix agent的用户有只读权限：
chmod 644 server.xml
3）日志文件对zabbix用户可读写，手动执行命令后都需要执行如下赋权命令：
chmod 666 /tmp/zabbix_tomcat_info.log  
4）参考：
https://github.com/qiueer/zabbix/blob/master/Tomcat/usage.txt
```

**Comment by RyanZhang2015** [comment]
2）修改tomcat配置文件权限，让运行zabbix agent的用户有只读权限：
chmod 644 server.xml
3）日志文件对zabbix用户可读写，手动执行命令后都需要执行如下赋权命令：
chmod 666 /tmp/zabbix_tomcat_info.log 
以上两点已经设置过，还是同样的错误。
特别的一点是当时 我只设置一个tomcat实例的JMX时例如tomcat 8090, python tomcat.py --list可以得到结果也没抛出错误。但当我设置tomcat 8091的JMX后，再次运行python tomcat.py --list会得到上面的错误。
4）参考：
https://github.com/qiueer/zabbix/blob/master/Tomcat/usage.txt
这点已排查过。

**Comment by qiueer** [comment]
已解决。
