### ISSUE TITLE
log 文件超过设定大小时，rename 报错。

### ISSUE THREAD

**Issue by fireice009** [qiueer/zabbix#4]
121:20170308:012932.050 error reason for "dev108.dj.com:custom.redis.item[6380,used_memory]" changed: Received value [Traceback (most recent call last):  File "/usr/lib64/python2.7/logging/handlers.py", line 77, in emit    self.doRollover()  File "/usr/lib64/python2.7/logging/handlers.py", line 140, in doRollover    os.rename(self.baseFilename, dfn)OSError: [Errno 1] Operation not permittedLogged from file slog.py, line 13281524] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

**Comment by qiueer** [comment]
应该是权限问题，执行如下命令后再试试：
chmod 777 /tmp/.zabbix_*.{log,txt}
chmod 777 /tmp/zabbix_*.{txt,log}

手动执行脚本后，为了避免因权限导致的错误，最好都执行一下上面的命令。

**Comment by fireice009** [comment]
文件超过大小后会新建一个的吧？
文件没创建出来，能修改权限吗？

[root@localhost scripts]# chmod 777 /tmp/.zabbix_.{log,txt}
chmod: 无法访问"/tmp/.zabbix_.log": 没有那个文件或目录
chmod: 无法访问"/tmp/.zabbix_.txt": 没有那个文件或目录
[root@localhost scripts]# chmod 777 /tmp/zabbix_.{txt,log}
chmod: 无法访问"/tmp/zabbix_.txt": 没有那个文件或目录
chmod: 无法访问"/tmp/zabbix_.log": 没有那个文件或目录

**Comment by qiueer** [comment]
github显示少了个通配符，正确应该是执行如下命令：
```
chmod 777 /tmp/.zabbix_*.{log,txt}
chmod 777 /tmp/zabbix_*.{txt,log}
```

日志文件超过5M后，会先rename，然后再新建。以下是日志滚动的设定，每个日志文件最大为5M，保存两份：
```
self._logger = slog(self._logpath, debug=debug, size=5, count=2)
```

**Comment by fireice009** [comment]
仔细看了下，不是权限的问题。
`is not suitable for value type [Numeric (unsigned)] and data type [Decimal]`
目测是json的序列化问题。

**Comment by qiueer** [comment]
应该是权限问题的，执行到一半可以异常了，导致输出的内容并非json。切换到手动档，用普通帐号执行，debug模式




发自网易邮箱大师
在2017年04月10日 17:16，fireice009 写道：

仔细看了下，不是权限的问题。
is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
目测是json的序列化问题。

**Comment by fireice009** [comment]
嗯，看错了。原评论已经删除。
