### ISSUE TITLE
item传参数问题

### ISSUE THREAD

**Issue by shenxiwen** [qiueer/zabbix#5]
你好！
   我用了你的JVM监控模板和py脚本，但是我发现模板传给agent的变量不能一一对应 $1 $2 $3
用了双引号将第1个参数引起来，但这个item还是被解析成了多个参数 _
例如：zabbix_get -s  127.0.0.1  -k jmx.jvm.item["java.lang:type=GarbageCollectorname=PS Scavenge",CollectionTime,12345]

我用了另一个脚本来输出接受到的参数
输出结果为
$1 ==> java.lang:type=GarbageCollectorname=PS
$2 ==> Scavenge
$3 ==> CollectionTime

$3应该对应的是12345对吧。
您 知道怎么解决这个问题吗

**Comment by qiueer** [comment]
Linux命令后，空格注意要转义哈




发自网易邮箱大师
在2017年04月20日 18:42，shenxiwen 写道：

你好！
我用了你的JVM监控模板和py脚本，但是我发现模板传给agent的变量不能一一对应 $1 $2 $3
用了双引号将第1个参数引起来，但这个item还是被解析成了多个参数 _
例如：zabbix_get -s 127.0.0.1 -k jmx.jvm.item["java.lang:type=GarbageCollectorname=PS Scavenge",CollectionTime,12345]

我用了另一个脚本来输出接受到的参数
输出结果为
$1 ==> java.lang:type=GarbageCollectorname=PS
$2 ==> Scavenge
$3 ==> CollectionTime

$3应该对应的是12345对吧。
您 知道怎么解决这个问题吗

**Comment by qiueer** [comment]
Linux命令行，空格要转义




发自网易邮箱大师
在2017年04月20日 22:30，邱景钦 写道：
Linux命令后，空格注意要转义哈




发自网易邮箱大师
在2017年04月20日 18:42，shenxiwen 写道：

你好！
我用了你的JVM监控模板和py脚本，但是我发现模板传给agent的变量不能一一对应 $1 $2 $3
用了双引号将第1个参数引起来，但这个item还是被解析成了多个参数 _
例如：zabbix_get -s 127.0.0.1 -k jmx.jvm.item["java.lang:type=GarbageCollectorname=PS Scavenge",CollectionTime,12345]

我用了另一个脚本来输出接受到的参数
输出结果为
$1 ==> java.lang:type=GarbageCollectorname=PS
$2 ==> Scavenge
$3 ==> CollectionTime

$3应该对应的是12345对吧。
您 知道怎么解决这个问题吗
