### ISSUE TITLE
咨询下tomcat问题

### ISSUE THREAD

**Issue by 1981385824** [qiueer/zabbix#53]
问下为啥tomcat界面上的监控指标值都是0，脚本输出的值正常与jconsole一致，zabbix_get获取的值也正常
![Uploading JJ15R1I`ODJ4T$4G2GO8SAG.png…]()

**Comment by qiueer** [comment]
我看不到图。可以看看item的计算方式，比如是否是delta方式的？

**Comment by 1981385824** [comment]
感谢回复，情况是这样子的，python命令执行正常脚本没问题应该，zabbix_get也能正常获取数据item配置应该没啥问题，item的配置有和jconsole对比过，现象只有界面上的tomcat各项指标都为0，未找到错误日志，可能我排查思路有问题。
下面附上几张图，请教下具体的排查思路
![问题现象](https://user-images.githubusercontent.com/37207464/77271121-ce71d300-6ce8-11ea-82ad-b3cc6e243cda.png
![具体某个item配置](https://user-images.githubusercontent.com/37207464/77271155-e9444780-6ce8-11ea-89a7-039eef55df2e.png)
![jconsole监控数据](https://user-images.githubusercontent.com/37207464/77271158-ec3f3800-6ce8-11ea-8d77-608fdfca520e.png)

)

**Comment by 1981385824** [comment]
[

> 感谢回复，情况是这样子的，python命令执行正常脚本没问题应该，zabbix_get也能正常获取数据item配置应该没啥问题，item的配置有和jconsole对比过，现象只有界面上的tomcat某些指标都为0，未找到错误日志，可能我排查思路有问题。
> 下面附上几张图，请教下具体的排查思路
> ！[问题现象]（[https://user-images.githubusercontent.com/37207464/77271121- ce71d300-6ce8-11ea-82ad-b3cc6e243cda.png](https://user-images.githubusercontent.com/37207464/77271121-ce71d300-6ce8-11ea-82ad-b3cc6e243cda.png)
> ![具体某个项目配置](https://user-images.githubusercontent.com/37207464/77271155-e9444780-6ce8-11ea-89a7-039eef55df2e.png)
> ![jconsole监控数据](https://user-images.githubusercontent.com/37207464/77271158-ec3f3800-6ce8-11ea-8d77-608fdfca520e.png)
> 
> ）

**Comment by 1981385824** [comment]
图片应该能看到了

**Comment by qiueer** [comment]
如果符合下面的情况：
1）root用户下，python执行脚本正常
2）zabbix_agent是用zabbix用户执行
多半是权限问题，如果是这种情况，解决思路是授权相关目录及文件所必需的权限

**Comment by 1981385824** [comment]
谢谢了哈，我在自己尝试下

**Comment by 1981385824** [comment]
问题解决，后面发现部分监控项是可以取到值的，而部分获取不到，然后把获取不到的item都删了在手动配置就可以获取到了，具体什么原因导致的还不清楚
