### ISSUE TITLE
which("java")获取失败

### ISSUE THREAD

**Issue by pipidoudou** [qiueer/zabbix#6]
本地以root账号运行成功，但从server端执行get的时候报错，看日志发现java执行路径未获取成功。[2017-05-16 10:45:49] INFO
beanstr   : java.lang:type=Memory
key       : ObjectPendingFinalizationCount
cmdstr    : **None -jar /etc/zabbix/jvm/cmdline-jmxclient-0.10.3.jar - localhost:12001 'java.lang:type=Memory' 'ObjectPendingFinalizationCount'**
ret       : 0
stdo      : 
stde      : /bin/sh: None: command not found

**Comment by qiueer** [comment]
你运行在zabbix用户吗，检查一下zabbix的PATH里面是否包含java路径？如果没有，在zabbix home目录下，编辑类似.bash_profile，.bashrc文件，将java路径配置上去，然后断开终端再登陆，执行java -version看是否正常。
