### ISSUE TITLE
获取数据失败

### ISSUE THREAD

**Issue by jimmi1228** [qiueer/zabbix#7]
您好，近期要求对jvm进行监控，按照你的监控步骤测试了下，结果在zabbix_jvm_info.log报出以下错误：
[2017-05-24 15:55:25] INFO
beanstr   : java.lang:type=GarbageCollector,name=MarkSweepCompact
key       : CollectionTime
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=MarkSweepCompact' 'CollectionTime'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:27] INFO
beanstr   : java.lang:type=GarbageCollector,name=ParNew
key       : CollectionCount
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=ParNew' 'CollectionCount'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:27] INFO
beanstr   : java.lang:type=GarbageCollector,name=ParNew
key       : CollectionTime
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=ParNew' 'CollectionTime'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:29] INFO
beanstr   : java.lang:type=GarbageCollector,name=PS
key       : CollectionCount
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=PS' 'CollectionCount'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:29] INFO
beanstr   : java.lang:type=GarbageCollector,name=PS
key       : CollectionTime
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=PS' 'CollectionTime'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:31] INFO
beanstr   : java.lang:type=GarbageCollector,name=PS
key       : CollectionCount
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=PS' 'CollectionCount'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:31] INFO
beanstr   : java.lang:type=GarbageCollector,name=PS
key       : CollectionTime
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=GarbageCollector,name=PS' 'CollectionTime'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:33] INFO
beanstr   : java.lang:type=Memory
key       : HeapMemoryUsage.committed
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=Memory' 'HeapMemoryUsage'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)
[2017-05-24 15:55:33] INFO
beanstr   : java.lang:type=Memory
key       : HeapMemoryUsage.max
cmdstr    : /usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 'java.lang:type=Memory' 'HeapMemoryUsage'
ret       : 0
stdo      :
stde      : Exception in thread "main" java.lang.NoClassDefFoundError: javax.management.remote.JMXServiceURLat org.archive.jmx.Client.execute(Client.java:223)at org.archive.jmx.Client.main(Client.java:154)

另外zabbix_server.log中：
[root@T-02 ~]# tail -f /tmp/zabbix_server.log
  1653:20170524:152547.650 item "T-02:jmx.jvm.item["java.lang:type=MemoryPool,name=Code Cache",Usage.max,12345]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1654:20170524:152550.269 item "T-02:jmx.jvm.item["java.lang:type=MemoryPool,name=Perm Gen",Usage.max,12345]" became not supported: Received value[] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1654:20170524:152553.280 item "T-02:jmx.jvm.item["java.lang:type=MemoryPool,name=PS Old Gen",Usage.max,12345]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1652:20170524:152556.663 item "T-02:jmx.jvm.item["java.lang:type=MemoryPool,name=PS Perm Gen",Usage.max,12345]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1654:20170524:152559.291 item "T-02:jmx.jvm.item["java.lang:type=MemoryPool,name=Tenured Gen",Usage.max,12345]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1654:20170524:152601.298 item "T-02:jmx.jvm.item["java.lang:type=OperatingSystem",MaxFileDescriptorCount,12345]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
  1648:20170524:153142.003 executing housekeeper
  1648:20170524:153142.014 housekeeper [deleted 0 hist/trends, 0 items, 0 events, 0 problems, 0 sessions, 0 alarms, 0 audit items in 0.008820 sec, idle for 1 hour(s)]
  1639:20170524:154819.168 Zabbix agent item "jmx.jvm.discovery" on host "T-02" failed: first network error, wait for 15 seconds

zabbix_agentd.conf 配置信息如下：
##jvm
UserParameter=jmx.jvm.discovery, python /usr/local/zabbix/scripts/jvm.py --list
UserParameter=jmx.jvm.item[*],python /usr/local/zabbix/scripts/jvm.py -b $1 -k "$2" -p $3

$1 $2 $3试图都加了双引号，但是没有解决问题。页面上获取不到数据，请问下大致上什么原因导致的？
java:1.8

**Comment by qiueer** [comment]
按下面操作看看
```
1）在zabbix server上执行下面命令看看输出什么，正常是一带有JMX端口信息的JSON串：
zabbix_get -s YOUR_IP_OR_HOST -k "jmx.jvm.discovery"
2）到这台装有zabbix agent的主机上执行如下命令，看看输出是什么：
java -version && ps -ef | grep java | grep -v grep  && netstat -nlpt 
/usr/bin/java -jar /usr/local/zabbix/scripts/cmdline-jmxclient-0.10.3.jar - localhost:12345 java.lang:type=Memory NonHeapMemoryUsage
```

**Comment by jimmi1228** [comment]
之前用这种方式取值#zabbix_get -s 192.168.40.217 -k jmx.jvm.item[java.lang:type='Memory name=HeapMemoryUsage',committed,12345] 没有数据返回为空。
后来调整这种方式就有了#zabbix_get -s 192.168.40.217 -k jmx.jvm.item['java.lang:type=Memory','HeapMemoryUsage.committed',12345]，不过不清楚为什么执行这条命令获取到数据后，日志文件中其它的也都有数据了，怪怪的。

**Comment by qiueer** [comment]
应该做了其他操作了吧，例如把日志文件权限调整了？
key名，你用zabbix_get测试的时候，最好看下模板中提供的key名，我做了优化的，如果还不明白，就看下源码，或者从日志中找到对应的cmdstr，手动执行看下效果，方法很多，了解原理和这么做的思想，很简单。

**Comment by hanlln1** [comment]
![default](https://user-images.githubusercontent.com/16384111/34985028-c571da80-faed-11e7-99ac-8e82a4bb7609.png)

**Comment by hanlln1** [comment]
执行命令的时候提示的是py脚本的错误
