### ISSUE TITLE
问题如下：

### ISSUE THREAD

**Issue by jimmi1228** [qiueer/zabbix#8]
您好，前几天按照所给的方式已经可以正常显示数据了，但是还有很多无法获取到数据，这个是不是要在java配置？
另外写入到/tmp/zabbix_jvm_info.log 这个文件的信息，能不能调整为使用crontab方式每分钟获取一次，获取到的数据覆盖上一次的，这样文件不会慢慢增大，您的方式是把获取到的数据追加进去，一周后发现这个文件已经几十M了。

**Comment by qiueer** [comment]
1）获取不到数据的item，需要看下你的java应用是不是支持。例如JVM有多种GC算法，但同一时间只有一种有效，我提供的模板对大部分常用的GC算法都适用的，可以把不适用的禁止；
2）/tmp/zabbix_jvm_info.log文件是日志文件，在zabbix的前端可以通过修改item的采样频率决定多久写入一次（zabbix master会读取DB获取这个频率，然后进行数据采集，注意不同item的频率可能不同）。跟crontab关系不大。不覆盖写入，是为了留痕，追查问题有用。文件大小不会太大，对这个日志文件，内容是滚动的，日志总量不会超过25M，因为每个日志文件最大设置为5M，只保留5份：
```
self._logger = slog(self._logpath, debug=debug, size=5, count=5)
```
