### ISSUE TITLE
数据库获取数据为空

### ISSUE THREAD

**Issue by yanyupan** [qiueer/zabbix#9]
主从复制延时以及主从复制状态获取数据为空，其它数据正常。/tmp/.zabbix_mysql_variables_slave_status_3306.txt没有SHOW SLAVE STATUS;的相关数值，感觉是存入文件时有问题

**Comment by qiueer** [comment]
需确认下，需采集数据的主机上MySQL实例是作为Slave的吗

**Comment by yanyupan** [comment]
是的

**Comment by yanyupan** [comment]
执行 python mysql_all.py -k is_replication -d有显示SHOW SLAVE STATUS;的相关数据：
Tc_log_max_pages_used	0
Tc_log_page_size	0
Tc_log_page_waits	0
Threads_cached	2
Threads_connected	1
Threads_created	3
Threads_running	1
Uptime	121678
Uptime_since_flush_status	121678
Slave_IO_State	Master_Host	Master_User	Master_Port	Connect_Retry	Master_Log_File	Read_Master_Log_Pos	Relay_Log_File	Relay_Log_Pos	Relay_Master_Log_File	Slave_IO_Running	Slave_SQL_Running	Replicate_Do_DB	Replicate_Ignore_DB	Replicate_Do_Table	Replicate_Ignore_Table	Replicate_Wild_Do_Table	Replicate_Wild_Ignore_Table	Last_Errno	Last_Error	Skip_Counter	Exec_Master_Log_Pos	Relay_Log_Space	Until_Condition	Until_Log_File	Until_Log_Pos	Master_SSL_Allowed	Master_SSL_CA_File	Master_SSL_CA_Path	Master_SSL_Cert	Master_SSL_Cipher	Master_SSL_Key	Seconds_Behind_Master	Master_SSL_Verify_Server_Cert	Last_IO_Errno	Last_IO_Error	Last_SQL_Errno	Last_SQL_Error	Replicate_Ignore_Server_Ids	Master_Server_Id	Master_UUID	Master_Info_File	SQL_Delay	SQL_Remaining_Delay	Slave_SQL_Running_State	Master_Retry_Count	Master_Bind	Last_IO_Error_Timestamp	Last_SQL_Error_Timestamp	Master_SSL_Crl	Master_SSL_Crlpath	Retrieved_Gtid_Set	Executed_Gtid_Set	Auto_Position
Waiting for master to send event	192.168.99.38	syc	3306	60	mysql-bin.000011	861039692	XMLT-DB-39-relay-bin.000049	38519110	mysql-bin.000011	Yes	Yes						mysql.%,information_schema.%,performance_schema.%	0		0	861037966	861040511	None		0	No						0	No	0		0			38	d2f18509-19ae-11e7-bfa9-246e965a0610	mysql.slave_master_info	0	NULL	Slave has read all relay log; waiting for the slave I/O thread to update it	86400						d2f18509-19ae-11e7-bfa9-246e965a0610:1-80037	d05cf0f0-19c5-11e7-8040-246e9659bd50:1-29,\nd2f18509-19ae-11e7-bfa9-246e965a0610:1-80037	1
    stde: Warning: Using a password on the command line interface can be insecure.
 retcode: 0

[2017-06-01 09:20:16] INFO
     msg: Try To Get From Cache File: /tmp/.zabbix_mysql_variables_slave_status_3306.txt
     key: slave_sql_running
   value: None
但文件/tmp/.zabbix_mysql_variables_slave_status_3306.txt里头没有记录

**Comment by qiueer** [comment]
执行下面的命令看下输出是什么：
```
python mysql_all.py -k is_replication -d -f
```

**Comment by yanyupan** [comment]
输出如下：
...................................
Ssl_used_session_cache_entries	0
Ssl_verify_depth	0
Ssl_verify_mode	0
Ssl_version	
Table_locks_immediate	47106
Table_locks_waited	0
Table_open_cache_hits	47936
Table_open_cache_misses	1276
Table_open_cache_overflows	0
Tc_log_max_pages_used	0
Tc_log_page_size	0
Tc_log_page_waits	0
Threads_cached	2
Threads_connected	1
Threads_created	3
Threads_running	1
Uptime	123110
Uptime_since_flush_status	123110
Slave_IO_State	Master_Host	Master_User	Master_Port	Connect_Retry	Master_Log_File	Read_Master_Log_Pos	Relay_Log_File	Relay_Log_Pos	Relay_Master_Log_File	Slave_IO_Running	Slave_SQL_Running	Replicate_Do_DB	Replicate_Ignore_DB	Replicate_Do_Table	Replicate_Ignore_Table	Replicate_Wild_Do_Table	Replicate_Wild_Ignore_Table	Last_Errno	Last_Error	Skip_Counter	Exec_Master_Log_Pos	Relay_Log_Space	Until_Condition	Until_Log_File	Until_Log_Pos	Master_SSL_Allowed	Master_SSL_CA_File	Master_SSL_CA_Path	Master_SSL_Cert	Master_SSL_Cipher	Master_SSL_Key	Seconds_Behind_Master	Master_SSL_Verify_Server_Cert	Last_IO_Errno	Last_IO_Error	Last_SQL_Errno	Last_SQL_Error	Replicate_Ignore_Server_Ids	Master_Server_Id	Master_UUID	Master_Info_File	SQL_Delay	SQL_Remaining_Delay	Slave_SQL_Running_State	Master_Retry_Count	Master_Bind	Last_IO_Error_Timestamp	Last_SQL_Error_Timestamp	Master_SSL_Crl	Master_SSL_Crlpath	Retrieved_Gtid_Set	Executed_Gtid_Set	Auto_Position
Waiting for master to send event	192.168.99.38	syc	3306	60	mysql-bin.000011	862023821	XMLT-DB-39-relay-bin.000049	39504965	mysql-bin.000011	Yes	Yes						mysql.%,information_schema.%,performance_schema.%	0		0	862023821	862024640	None		0	No						0	No	0		0			38	d2f18509-19ae-11e7-bfa9-246e965a0610	mysql.slave_master_info	0	NULL	Slave has read all relay log; waiting for the slave I/O thread to update it	86400						d2f18509-19ae-11e7-bfa9-246e965a0610:1-80085	d05cf0f0-19c5-11e7-8040-246e9659bd50:1-29,\nd2f18509-19ae-11e7-bfa9-246e965a0610:1-80085	1
    stde: Warning: Using a password on the command line interface can be insecure.
 retcode: 0

**Comment by qiueer** [comment]
stdo不完整吧，另cmdstr的输出是什么？

**Comment by yanyupan** [comment]
stdo是不完整，前面的我省略了！cmdstr输出是：
cmdstr: /usr/local/mysql/bin/mysql -hlocalhost -P3306 -uzabbix -pPY9y:o6acP -e "SHOW VARIABLES; SHOW GLOBAL STATUS; SHOW SLAVE STATUS;"

**Comment by qiueer** [comment]
初步判断，应该是MySQL主从配置不成功导致。

**Comment by qiueer** [comment]
登陆MySQL，执行如下命令，看下输出看是否主从配置的问题：
```
show slave status \G;
```

**Comment by yanyupan** [comment]
mysql> SHOW SLAVE STATUS\G;
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 192.168.99.38
                  Master_User: syc
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000011
          Read_Master_Log_Pos: 862967911
               Relay_Log_File: XMLT-DB-39-relay-bin.000049
                Relay_Log_Pos: 40449055
        Relay_Master_Log_File: mysql-bin.000011
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table: mysql.%,information_schema.%,performance_schema.%
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 862967911
              Relay_Log_Space: 862968730
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 38
                  Master_UUID: d2f18509-19ae-11e7-bfa9-246e965a0610
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set: d2f18509-19ae-11e7-bfa9-246e965a0610:1-80111
            Executed_Gtid_Set: d05cf0f0-19c5-11e7-8040-246e9659bd50:1-29,
d2f18509-19ae-11e7-bfa9-246e965a0610:1-80111
                Auto_Position: 1
1 row in set (0.00 sec)

ERROR:
No query specified

**Comment by qiueer** [comment]
```
1）执行以下命令：   
python mysql_all.py -k is_replication -d -f >/tmp/zabbix_mysql_exe_result_`date +'%Y%m%d%H%M%S'`  
2）能否将/tmp/zabbix_mysql_exe_result_*.txt，/tmp/.zabbix_mysql_variables_slave_status_3306.txt这两个问文件发送到我的邮箱：86877295@qq.com  
```

**Comment by qiueer** [comment]
好奇怪，show slave status每行显示的内容不是key，value的方式显示，你登陆mysql，执行如下命令，看下结果：
```
SHOW SLAVE STATUS;
```

**Comment by qiueer** [comment]
临时按照如下方法修改下看：
```
1）备份  
cp mysql_all.py mysql_all_old.py  
2）调整源码  
将75行改为：line_ary = re.split(r"[\s|\||:|;|,]+", line)   
将89行改为：cmdstr = "SHOW VARIABLES; SHOW GLOBAL STATUS; SHOW SLAVE STATUS\G"
```

**Comment by yanyupan** [comment]
谢谢，按以上方法问题解决
